USE [master]
GO

/****** Object:  Database [NUCodeTasks]    Script Date: 11/9/2017 6:52:13 PM ******/
CREATE DATABASE [NUCodeTasks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NUCodeTasks', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.DBT130\MSSQL\DATA\NUCodeTasks.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'NUCodeTasks_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.DBT130\MSSQL\DATA\NUCodeTasks_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [NUCodeTasks] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NUCodeTasks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NUCodeTasks] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NUCodeTasks] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NUCodeTasks] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NUCodeTasks] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NUCodeTasks] SET ARITHABORT OFF 
GO

ALTER DATABASE [NUCodeTasks] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NUCodeTasks] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NUCodeTasks] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NUCodeTasks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NUCodeTasks] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NUCodeTasks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NUCodeTasks] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NUCodeTasks] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NUCodeTasks] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NUCodeTasks] SET  DISABLE_BROKER 
GO

ALTER DATABASE [NUCodeTasks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NUCodeTasks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NUCodeTasks] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NUCodeTasks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NUCodeTasks] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NUCodeTasks] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NUCodeTasks] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NUCodeTasks] SET RECOVERY FULL 
GO

ALTER DATABASE [NUCodeTasks] SET  MULTI_USER 
GO

ALTER DATABASE [NUCodeTasks] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NUCodeTasks] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NUCodeTasks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NUCodeTasks] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [NUCodeTasks] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NUCodeTasks] SET  READ_WRITE 
GO


USE [NUCodeTasks]
GO

/****** Object:  Table [dbo].[Tasks]    Script Date: 11/9/2017 6:52:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Tasks](
	[id] [int] NOT NULL,
	[TaskName] [varchar](max) NULL,
	[DueDate] [datetime] NULL,
	[DateStarted] [datetime] NULL,
	[DateCompleted] [datetime] NULL,
	[EstimatedDuration] [varchar](max) NULL,
	[isCompleted] [bit] NULL,
	[Description] [varchar](max) NULL,
	[Tag1] [varchar](max) NULL,
	[Tag2] [varchar](max) NULL,
	[Tag3] [varchar](max) NULL,
 CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


